// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flow/v1/flow.proto

package flowv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "flowcli/internal/pb/flow/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FlowServiceName is the fully-qualified name of the FlowService service.
	FlowServiceName = "flow.v1.FlowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FlowServiceListProjectsProcedure is the fully-qualified name of the FlowService's ListProjects
	// RPC.
	FlowServiceListProjectsProcedure = "/flow.v1.FlowService/ListProjects"
	// FlowServiceGetSnapshotProcedure is the fully-qualified name of the FlowService's GetSnapshot RPC.
	FlowServiceGetSnapshotProcedure = "/flow.v1.FlowService/GetSnapshot"
	// FlowServiceListEventsProcedure is the fully-qualified name of the FlowService's ListEvents RPC.
	FlowServiceListEventsProcedure = "/flow.v1.FlowService/ListEvents"
	// FlowServiceSearchProcedure is the fully-qualified name of the FlowService's Search RPC.
	FlowServiceSearchProcedure = "/flow.v1.FlowService/Search"
	// FlowServicePollChangesProcedure is the fully-qualified name of the FlowService's PollChanges RPC.
	FlowServicePollChangesProcedure = "/flow.v1.FlowService/PollChanges"
	// FlowServiceWatchProcedure is the fully-qualified name of the FlowService's Watch RPC.
	FlowServiceWatchProcedure = "/flow.v1.FlowService/Watch"
	// FlowServiceCreateNodeProcedure is the fully-qualified name of the FlowService's CreateNode RPC.
	FlowServiceCreateNodeProcedure = "/flow.v1.FlowService/CreateNode"
	// FlowServiceUpdateNodeProcedure is the fully-qualified name of the FlowService's UpdateNode RPC.
	FlowServiceUpdateNodeProcedure = "/flow.v1.FlowService/UpdateNode"
	// FlowServiceDeleteNodeProcedure is the fully-qualified name of the FlowService's DeleteNode RPC.
	FlowServiceDeleteNodeProcedure = "/flow.v1.FlowService/DeleteNode"
	// FlowServiceSetStatusProcedure is the fully-qualified name of the FlowService's SetStatus RPC.
	FlowServiceSetStatusProcedure = "/flow.v1.FlowService/SetStatus"
	// FlowServiceReportConditionProcedure is the fully-qualified name of the FlowService's
	// ReportCondition RPC.
	FlowServiceReportConditionProcedure = "/flow.v1.FlowService/ReportCondition"
	// FlowServiceSetVerdictProcedure is the fully-qualified name of the FlowService's SetVerdict RPC.
	FlowServiceSetVerdictProcedure = "/flow.v1.FlowService/SetVerdict"
	// FlowServiceAddCommentProcedure is the fully-qualified name of the FlowService's AddComment RPC.
	FlowServiceAddCommentProcedure = "/flow.v1.FlowService/AddComment"
	// FlowServiceAddDependencyProcedure is the fully-qualified name of the FlowService's AddDependency
	// RPC.
	FlowServiceAddDependencyProcedure = "/flow.v1.FlowService/AddDependency"
	// FlowServiceRemoveDependencyProcedure is the fully-qualified name of the FlowService's
	// RemoveDependency RPC.
	FlowServiceRemoveDependencyProcedure = "/flow.v1.FlowService/RemoveDependency"
	// FlowServiceUndoProcedure is the fully-qualified name of the FlowService's Undo RPC.
	FlowServiceUndoProcedure = "/flow.v1.FlowService/Undo"
	// FlowServiceMoveNodeProcedure is the fully-qualified name of the FlowService's MoveNode RPC.
	FlowServiceMoveNodeProcedure = "/flow.v1.FlowService/MoveNode"
	// FlowServiceCreateProjectProcedure is the fully-qualified name of the FlowService's CreateProject
	// RPC.
	FlowServiceCreateProjectProcedure = "/flow.v1.FlowService/CreateProject"
	// FlowServiceUpdateProjectProcedure is the fully-qualified name of the FlowService's UpdateProject
	// RPC.
	FlowServiceUpdateProjectProcedure = "/flow.v1.FlowService/UpdateProject"
	// FlowServiceArchiveProjectProcedure is the fully-qualified name of the FlowService's
	// ArchiveProject RPC.
	FlowServiceArchiveProjectProcedure = "/flow.v1.FlowService/ArchiveProject"
)

// FlowServiceClient is a client for the flow.v1.FlowService service.
type FlowServiceClient interface {
	// Lists projects the client can open.
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	// Loads a full, consistent snapshot of one project.
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error)
	// Pages the event log for a project.
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	// Full-text searches nodes within a project.
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
	// Unary forward poll of the event log — the stateless substitute for Watch.
	PollChanges(context.Context, *connect.Request[v1.PollChangesRequest]) (*connect.Response[v1.PollChangesResponse], error)
	// The one long-lived call. Every client holds exactly one.
	Watch(context.Context, *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.WatchResponse], error)
	// Creates a node.
	CreateNode(context.Context, *connect.Request[v1.CreateNodeRequest]) (*connect.Response[v1.CreateNodeResponse], error)
	// Updates editable fields of a node.
	UpdateNode(context.Context, *connect.Request[v1.UpdateNodeRequest]) (*connect.Response[v1.UpdateNodeResponse], error)
	// Deletes a node and its subtree.
	DeleteNode(context.Context, *connect.Request[v1.DeleteNodeRequest]) (*connect.Response[v1.DeleteNodeResponse], error)
	// Sets a node's declared status.
	SetStatus(context.Context, *connect.Request[v1.SetStatusRequest]) (*connect.Response[v1.SetStatusResponse], error)
	// Records an agent's condition report.
	ReportCondition(context.Context, *connect.Request[v1.ReportConditionRequest]) (*connect.Response[v1.ReportConditionResponse], error)
	// Records a human's verdict over an agent report.
	SetVerdict(context.Context, *connect.Request[v1.SetVerdictRequest]) (*connect.Response[v1.SetVerdictResponse], error)
	// Adds a comment to a node.
	AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error)
	// Adds a dependency edge.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// Removes a dependency edge.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// Reverses a prior event.
	Undo(context.Context, *connect.Request[v1.UndoRequest]) (*connect.Response[v1.UndoResponse], error)
	// Moves a node to a new parent and/or changes its kind.
	MoveNode(context.Context, *connect.Request[v1.MoveNodeRequest]) (*connect.Response[v1.MoveNodeResponse], error)
	// Creates a project (namespace op; returns the created Project).
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	// Edits a project's name/description.
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	// Archives or un-archives a project.
	ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error)
}

// NewFlowServiceClient constructs a client for the flow.v1.FlowService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FlowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	flowServiceMethods := v1.File_flow_v1_flow_proto.Services().ByName("FlowService").Methods()
	return &flowServiceClient{
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+FlowServiceListProjectsProcedure,
			connect.WithSchema(flowServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		getSnapshot: connect.NewClient[v1.GetSnapshotRequest, v1.GetSnapshotResponse](
			httpClient,
			baseURL+FlowServiceGetSnapshotProcedure,
			connect.WithSchema(flowServiceMethods.ByName("GetSnapshot")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+FlowServiceListEventsProcedure,
			connect.WithSchema(flowServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[v1.SearchRequest, v1.SearchResponse](
			httpClient,
			baseURL+FlowServiceSearchProcedure,
			connect.WithSchema(flowServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		pollChanges: connect.NewClient[v1.PollChangesRequest, v1.PollChangesResponse](
			httpClient,
			baseURL+FlowServicePollChangesProcedure,
			connect.WithSchema(flowServiceMethods.ByName("PollChanges")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.WatchRequest, v1.WatchResponse](
			httpClient,
			baseURL+FlowServiceWatchProcedure,
			connect.WithSchema(flowServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		createNode: connect.NewClient[v1.CreateNodeRequest, v1.CreateNodeResponse](
			httpClient,
			baseURL+FlowServiceCreateNodeProcedure,
			connect.WithSchema(flowServiceMethods.ByName("CreateNode")),
			connect.WithClientOptions(opts...),
		),
		updateNode: connect.NewClient[v1.UpdateNodeRequest, v1.UpdateNodeResponse](
			httpClient,
			baseURL+FlowServiceUpdateNodeProcedure,
			connect.WithSchema(flowServiceMethods.ByName("UpdateNode")),
			connect.WithClientOptions(opts...),
		),
		deleteNode: connect.NewClient[v1.DeleteNodeRequest, v1.DeleteNodeResponse](
			httpClient,
			baseURL+FlowServiceDeleteNodeProcedure,
			connect.WithSchema(flowServiceMethods.ByName("DeleteNode")),
			connect.WithClientOptions(opts...),
		),
		setStatus: connect.NewClient[v1.SetStatusRequest, v1.SetStatusResponse](
			httpClient,
			baseURL+FlowServiceSetStatusProcedure,
			connect.WithSchema(flowServiceMethods.ByName("SetStatus")),
			connect.WithClientOptions(opts...),
		),
		reportCondition: connect.NewClient[v1.ReportConditionRequest, v1.ReportConditionResponse](
			httpClient,
			baseURL+FlowServiceReportConditionProcedure,
			connect.WithSchema(flowServiceMethods.ByName("ReportCondition")),
			connect.WithClientOptions(opts...),
		),
		setVerdict: connect.NewClient[v1.SetVerdictRequest, v1.SetVerdictResponse](
			httpClient,
			baseURL+FlowServiceSetVerdictProcedure,
			connect.WithSchema(flowServiceMethods.ByName("SetVerdict")),
			connect.WithClientOptions(opts...),
		),
		addComment: connect.NewClient[v1.AddCommentRequest, v1.AddCommentResponse](
			httpClient,
			baseURL+FlowServiceAddCommentProcedure,
			connect.WithSchema(flowServiceMethods.ByName("AddComment")),
			connect.WithClientOptions(opts...),
		),
		addDependency: connect.NewClient[v1.AddDependencyRequest, v1.AddDependencyResponse](
			httpClient,
			baseURL+FlowServiceAddDependencyProcedure,
			connect.WithSchema(flowServiceMethods.ByName("AddDependency")),
			connect.WithClientOptions(opts...),
		),
		removeDependency: connect.NewClient[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse](
			httpClient,
			baseURL+FlowServiceRemoveDependencyProcedure,
			connect.WithSchema(flowServiceMethods.ByName("RemoveDependency")),
			connect.WithClientOptions(opts...),
		),
		undo: connect.NewClient[v1.UndoRequest, v1.UndoResponse](
			httpClient,
			baseURL+FlowServiceUndoProcedure,
			connect.WithSchema(flowServiceMethods.ByName("Undo")),
			connect.WithClientOptions(opts...),
		),
		moveNode: connect.NewClient[v1.MoveNodeRequest, v1.MoveNodeResponse](
			httpClient,
			baseURL+FlowServiceMoveNodeProcedure,
			connect.WithSchema(flowServiceMethods.ByName("MoveNode")),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+FlowServiceCreateProjectProcedure,
			connect.WithSchema(flowServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.UpdateProjectResponse](
			httpClient,
			baseURL+FlowServiceUpdateProjectProcedure,
			connect.WithSchema(flowServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		archiveProject: connect.NewClient[v1.ArchiveProjectRequest, v1.ArchiveProjectResponse](
			httpClient,
			baseURL+FlowServiceArchiveProjectProcedure,
			connect.WithSchema(flowServiceMethods.ByName("ArchiveProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// flowServiceClient implements FlowServiceClient.
type flowServiceClient struct {
	listProjects     *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	getSnapshot      *connect.Client[v1.GetSnapshotRequest, v1.GetSnapshotResponse]
	listEvents       *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	search           *connect.Client[v1.SearchRequest, v1.SearchResponse]
	pollChanges      *connect.Client[v1.PollChangesRequest, v1.PollChangesResponse]
	watch            *connect.Client[v1.WatchRequest, v1.WatchResponse]
	createNode       *connect.Client[v1.CreateNodeRequest, v1.CreateNodeResponse]
	updateNode       *connect.Client[v1.UpdateNodeRequest, v1.UpdateNodeResponse]
	deleteNode       *connect.Client[v1.DeleteNodeRequest, v1.DeleteNodeResponse]
	setStatus        *connect.Client[v1.SetStatusRequest, v1.SetStatusResponse]
	reportCondition  *connect.Client[v1.ReportConditionRequest, v1.ReportConditionResponse]
	setVerdict       *connect.Client[v1.SetVerdictRequest, v1.SetVerdictResponse]
	addComment       *connect.Client[v1.AddCommentRequest, v1.AddCommentResponse]
	addDependency    *connect.Client[v1.AddDependencyRequest, v1.AddDependencyResponse]
	removeDependency *connect.Client[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse]
	undo             *connect.Client[v1.UndoRequest, v1.UndoResponse]
	moveNode         *connect.Client[v1.MoveNodeRequest, v1.MoveNodeResponse]
	createProject    *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	updateProject    *connect.Client[v1.UpdateProjectRequest, v1.UpdateProjectResponse]
	archiveProject   *connect.Client[v1.ArchiveProjectRequest, v1.ArchiveProjectResponse]
}

// ListProjects calls flow.v1.FlowService.ListProjects.
func (c *flowServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// GetSnapshot calls flow.v1.FlowService.GetSnapshot.
func (c *flowServiceClient) GetSnapshot(ctx context.Context, req *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error) {
	return c.getSnapshot.CallUnary(ctx, req)
}

// ListEvents calls flow.v1.FlowService.ListEvents.
func (c *flowServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// Search calls flow.v1.FlowService.Search.
func (c *flowServiceClient) Search(ctx context.Context, req *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// PollChanges calls flow.v1.FlowService.PollChanges.
func (c *flowServiceClient) PollChanges(ctx context.Context, req *connect.Request[v1.PollChangesRequest]) (*connect.Response[v1.PollChangesResponse], error) {
	return c.pollChanges.CallUnary(ctx, req)
}

// Watch calls flow.v1.FlowService.Watch.
func (c *flowServiceClient) Watch(ctx context.Context, req *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.WatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// CreateNode calls flow.v1.FlowService.CreateNode.
func (c *flowServiceClient) CreateNode(ctx context.Context, req *connect.Request[v1.CreateNodeRequest]) (*connect.Response[v1.CreateNodeResponse], error) {
	return c.createNode.CallUnary(ctx, req)
}

// UpdateNode calls flow.v1.FlowService.UpdateNode.
func (c *flowServiceClient) UpdateNode(ctx context.Context, req *connect.Request[v1.UpdateNodeRequest]) (*connect.Response[v1.UpdateNodeResponse], error) {
	return c.updateNode.CallUnary(ctx, req)
}

// DeleteNode calls flow.v1.FlowService.DeleteNode.
func (c *flowServiceClient) DeleteNode(ctx context.Context, req *connect.Request[v1.DeleteNodeRequest]) (*connect.Response[v1.DeleteNodeResponse], error) {
	return c.deleteNode.CallUnary(ctx, req)
}

// SetStatus calls flow.v1.FlowService.SetStatus.
func (c *flowServiceClient) SetStatus(ctx context.Context, req *connect.Request[v1.SetStatusRequest]) (*connect.Response[v1.SetStatusResponse], error) {
	return c.setStatus.CallUnary(ctx, req)
}

// ReportCondition calls flow.v1.FlowService.ReportCondition.
func (c *flowServiceClient) ReportCondition(ctx context.Context, req *connect.Request[v1.ReportConditionRequest]) (*connect.Response[v1.ReportConditionResponse], error) {
	return c.reportCondition.CallUnary(ctx, req)
}

// SetVerdict calls flow.v1.FlowService.SetVerdict.
func (c *flowServiceClient) SetVerdict(ctx context.Context, req *connect.Request[v1.SetVerdictRequest]) (*connect.Response[v1.SetVerdictResponse], error) {
	return c.setVerdict.CallUnary(ctx, req)
}

// AddComment calls flow.v1.FlowService.AddComment.
func (c *flowServiceClient) AddComment(ctx context.Context, req *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error) {
	return c.addComment.CallUnary(ctx, req)
}

// AddDependency calls flow.v1.FlowService.AddDependency.
func (c *flowServiceClient) AddDependency(ctx context.Context, req *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return c.addDependency.CallUnary(ctx, req)
}

// RemoveDependency calls flow.v1.FlowService.RemoveDependency.
func (c *flowServiceClient) RemoveDependency(ctx context.Context, req *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return c.removeDependency.CallUnary(ctx, req)
}

// Undo calls flow.v1.FlowService.Undo.
func (c *flowServiceClient) Undo(ctx context.Context, req *connect.Request[v1.UndoRequest]) (*connect.Response[v1.UndoResponse], error) {
	return c.undo.CallUnary(ctx, req)
}

// MoveNode calls flow.v1.FlowService.MoveNode.
func (c *flowServiceClient) MoveNode(ctx context.Context, req *connect.Request[v1.MoveNodeRequest]) (*connect.Response[v1.MoveNodeResponse], error) {
	return c.moveNode.CallUnary(ctx, req)
}

// CreateProject calls flow.v1.FlowService.CreateProject.
func (c *flowServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// UpdateProject calls flow.v1.FlowService.UpdateProject.
func (c *flowServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// ArchiveProject calls flow.v1.FlowService.ArchiveProject.
func (c *flowServiceClient) ArchiveProject(ctx context.Context, req *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error) {
	return c.archiveProject.CallUnary(ctx, req)
}

// FlowServiceHandler is an implementation of the flow.v1.FlowService service.
type FlowServiceHandler interface {
	// Lists projects the client can open.
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	// Loads a full, consistent snapshot of one project.
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error)
	// Pages the event log for a project.
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	// Full-text searches nodes within a project.
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
	// Unary forward poll of the event log — the stateless substitute for Watch.
	PollChanges(context.Context, *connect.Request[v1.PollChangesRequest]) (*connect.Response[v1.PollChangesResponse], error)
	// The one long-lived call. Every client holds exactly one.
	Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.WatchResponse]) error
	// Creates a node.
	CreateNode(context.Context, *connect.Request[v1.CreateNodeRequest]) (*connect.Response[v1.CreateNodeResponse], error)
	// Updates editable fields of a node.
	UpdateNode(context.Context, *connect.Request[v1.UpdateNodeRequest]) (*connect.Response[v1.UpdateNodeResponse], error)
	// Deletes a node and its subtree.
	DeleteNode(context.Context, *connect.Request[v1.DeleteNodeRequest]) (*connect.Response[v1.DeleteNodeResponse], error)
	// Sets a node's declared status.
	SetStatus(context.Context, *connect.Request[v1.SetStatusRequest]) (*connect.Response[v1.SetStatusResponse], error)
	// Records an agent's condition report.
	ReportCondition(context.Context, *connect.Request[v1.ReportConditionRequest]) (*connect.Response[v1.ReportConditionResponse], error)
	// Records a human's verdict over an agent report.
	SetVerdict(context.Context, *connect.Request[v1.SetVerdictRequest]) (*connect.Response[v1.SetVerdictResponse], error)
	// Adds a comment to a node.
	AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error)
	// Adds a dependency edge.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// Removes a dependency edge.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// Reverses a prior event.
	Undo(context.Context, *connect.Request[v1.UndoRequest]) (*connect.Response[v1.UndoResponse], error)
	// Moves a node to a new parent and/or changes its kind.
	MoveNode(context.Context, *connect.Request[v1.MoveNodeRequest]) (*connect.Response[v1.MoveNodeResponse], error)
	// Creates a project (namespace op; returns the created Project).
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	// Edits a project's name/description.
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	// Archives or un-archives a project.
	ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error)
}

// NewFlowServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlowServiceHandler(svc FlowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	flowServiceMethods := v1.File_flow_v1_flow_proto.Services().ByName("FlowService").Methods()
	flowServiceListProjectsHandler := connect.NewUnaryHandler(
		FlowServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(flowServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceGetSnapshotHandler := connect.NewUnaryHandler(
		FlowServiceGetSnapshotProcedure,
		svc.GetSnapshot,
		connect.WithSchema(flowServiceMethods.ByName("GetSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceListEventsHandler := connect.NewUnaryHandler(
		FlowServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(flowServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceSearchHandler := connect.NewUnaryHandler(
		FlowServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(flowServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	flowServicePollChangesHandler := connect.NewUnaryHandler(
		FlowServicePollChangesProcedure,
		svc.PollChanges,
		connect.WithSchema(flowServiceMethods.ByName("PollChanges")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceWatchHandler := connect.NewServerStreamHandler(
		FlowServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(flowServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceCreateNodeHandler := connect.NewUnaryHandler(
		FlowServiceCreateNodeProcedure,
		svc.CreateNode,
		connect.WithSchema(flowServiceMethods.ByName("CreateNode")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceUpdateNodeHandler := connect.NewUnaryHandler(
		FlowServiceUpdateNodeProcedure,
		svc.UpdateNode,
		connect.WithSchema(flowServiceMethods.ByName("UpdateNode")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceDeleteNodeHandler := connect.NewUnaryHandler(
		FlowServiceDeleteNodeProcedure,
		svc.DeleteNode,
		connect.WithSchema(flowServiceMethods.ByName("DeleteNode")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceSetStatusHandler := connect.NewUnaryHandler(
		FlowServiceSetStatusProcedure,
		svc.SetStatus,
		connect.WithSchema(flowServiceMethods.ByName("SetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceReportConditionHandler := connect.NewUnaryHandler(
		FlowServiceReportConditionProcedure,
		svc.ReportCondition,
		connect.WithSchema(flowServiceMethods.ByName("ReportCondition")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceSetVerdictHandler := connect.NewUnaryHandler(
		FlowServiceSetVerdictProcedure,
		svc.SetVerdict,
		connect.WithSchema(flowServiceMethods.ByName("SetVerdict")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceAddCommentHandler := connect.NewUnaryHandler(
		FlowServiceAddCommentProcedure,
		svc.AddComment,
		connect.WithSchema(flowServiceMethods.ByName("AddComment")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceAddDependencyHandler := connect.NewUnaryHandler(
		FlowServiceAddDependencyProcedure,
		svc.AddDependency,
		connect.WithSchema(flowServiceMethods.ByName("AddDependency")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceRemoveDependencyHandler := connect.NewUnaryHandler(
		FlowServiceRemoveDependencyProcedure,
		svc.RemoveDependency,
		connect.WithSchema(flowServiceMethods.ByName("RemoveDependency")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceUndoHandler := connect.NewUnaryHandler(
		FlowServiceUndoProcedure,
		svc.Undo,
		connect.WithSchema(flowServiceMethods.ByName("Undo")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceMoveNodeHandler := connect.NewUnaryHandler(
		FlowServiceMoveNodeProcedure,
		svc.MoveNode,
		connect.WithSchema(flowServiceMethods.ByName("MoveNode")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceCreateProjectHandler := connect.NewUnaryHandler(
		FlowServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(flowServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceUpdateProjectHandler := connect.NewUnaryHandler(
		FlowServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(flowServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	flowServiceArchiveProjectHandler := connect.NewUnaryHandler(
		FlowServiceArchiveProjectProcedure,
		svc.ArchiveProject,
		connect.WithSchema(flowServiceMethods.ByName("ArchiveProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flow.v1.FlowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlowServiceListProjectsProcedure:
			flowServiceListProjectsHandler.ServeHTTP(w, r)
		case FlowServiceGetSnapshotProcedure:
			flowServiceGetSnapshotHandler.ServeHTTP(w, r)
		case FlowServiceListEventsProcedure:
			flowServiceListEventsHandler.ServeHTTP(w, r)
		case FlowServiceSearchProcedure:
			flowServiceSearchHandler.ServeHTTP(w, r)
		case FlowServicePollChangesProcedure:
			flowServicePollChangesHandler.ServeHTTP(w, r)
		case FlowServiceWatchProcedure:
			flowServiceWatchHandler.ServeHTTP(w, r)
		case FlowServiceCreateNodeProcedure:
			flowServiceCreateNodeHandler.ServeHTTP(w, r)
		case FlowServiceUpdateNodeProcedure:
			flowServiceUpdateNodeHandler.ServeHTTP(w, r)
		case FlowServiceDeleteNodeProcedure:
			flowServiceDeleteNodeHandler.ServeHTTP(w, r)
		case FlowServiceSetStatusProcedure:
			flowServiceSetStatusHandler.ServeHTTP(w, r)
		case FlowServiceReportConditionProcedure:
			flowServiceReportConditionHandler.ServeHTTP(w, r)
		case FlowServiceSetVerdictProcedure:
			flowServiceSetVerdictHandler.ServeHTTP(w, r)
		case FlowServiceAddCommentProcedure:
			flowServiceAddCommentHandler.ServeHTTP(w, r)
		case FlowServiceAddDependencyProcedure:
			flowServiceAddDependencyHandler.ServeHTTP(w, r)
		case FlowServiceRemoveDependencyProcedure:
			flowServiceRemoveDependencyHandler.ServeHTTP(w, r)
		case FlowServiceUndoProcedure:
			flowServiceUndoHandler.ServeHTTP(w, r)
		case FlowServiceMoveNodeProcedure:
			flowServiceMoveNodeHandler.ServeHTTP(w, r)
		case FlowServiceCreateProjectProcedure:
			flowServiceCreateProjectHandler.ServeHTTP(w, r)
		case FlowServiceUpdateProjectProcedure:
			flowServiceUpdateProjectHandler.ServeHTTP(w, r)
		case FlowServiceArchiveProjectProcedure:
			flowServiceArchiveProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlowServiceHandler struct{}

func (UnimplementedFlowServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.ListProjects is not implemented"))
}

func (UnimplementedFlowServiceHandler) GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.GetSnapshot is not implemented"))
}

func (UnimplementedFlowServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.ListEvents is not implemented"))
}

func (UnimplementedFlowServiceHandler) Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.Search is not implemented"))
}

func (UnimplementedFlowServiceHandler) PollChanges(context.Context, *connect.Request[v1.PollChangesRequest]) (*connect.Response[v1.PollChangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.PollChanges is not implemented"))
}

func (UnimplementedFlowServiceHandler) Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.WatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.Watch is not implemented"))
}

func (UnimplementedFlowServiceHandler) CreateNode(context.Context, *connect.Request[v1.CreateNodeRequest]) (*connect.Response[v1.CreateNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.CreateNode is not implemented"))
}

func (UnimplementedFlowServiceHandler) UpdateNode(context.Context, *connect.Request[v1.UpdateNodeRequest]) (*connect.Response[v1.UpdateNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.UpdateNode is not implemented"))
}

func (UnimplementedFlowServiceHandler) DeleteNode(context.Context, *connect.Request[v1.DeleteNodeRequest]) (*connect.Response[v1.DeleteNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.DeleteNode is not implemented"))
}

func (UnimplementedFlowServiceHandler) SetStatus(context.Context, *connect.Request[v1.SetStatusRequest]) (*connect.Response[v1.SetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.SetStatus is not implemented"))
}

func (UnimplementedFlowServiceHandler) ReportCondition(context.Context, *connect.Request[v1.ReportConditionRequest]) (*connect.Response[v1.ReportConditionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.ReportCondition is not implemented"))
}

func (UnimplementedFlowServiceHandler) SetVerdict(context.Context, *connect.Request[v1.SetVerdictRequest]) (*connect.Response[v1.SetVerdictResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.SetVerdict is not implemented"))
}

func (UnimplementedFlowServiceHandler) AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.AddComment is not implemented"))
}

func (UnimplementedFlowServiceHandler) AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.AddDependency is not implemented"))
}

func (UnimplementedFlowServiceHandler) RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.RemoveDependency is not implemented"))
}

func (UnimplementedFlowServiceHandler) Undo(context.Context, *connect.Request[v1.UndoRequest]) (*connect.Response[v1.UndoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.Undo is not implemented"))
}

func (UnimplementedFlowServiceHandler) MoveNode(context.Context, *connect.Request[v1.MoveNodeRequest]) (*connect.Response[v1.MoveNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.MoveNode is not implemented"))
}

func (UnimplementedFlowServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.CreateProject is not implemented"))
}

func (UnimplementedFlowServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.UpdateProject is not implemented"))
}

func (UnimplementedFlowServiceHandler) ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flow.v1.FlowService.ArchiveProject is not implemented"))
}
