// @generated by protoc-gen-connect-es v1.6.1
// @generated from file flow/v1/flow.proto (package flow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddCommentRequest, AddCommentResponse, AddDependencyRequest, AddDependencyResponse, ArchiveProjectRequest, ArchiveProjectResponse, CreateNodeRequest, CreateNodeResponse, CreateProjectRequest, CreateProjectResponse, DeleteNodeRequest, DeleteNodeResponse, GetSnapshotRequest, GetSnapshotResponse, ListEventsRequest, ListEventsResponse, ListProjectsRequest, ListProjectsResponse, MoveNodeRequest, MoveNodeResponse, PollChangesRequest, PollChangesResponse, RemoveDependencyRequest, RemoveDependencyResponse, ReportConditionRequest, ReportConditionResponse, SearchRequest, SearchResponse, SetStatusRequest, SetStatusResponse, SetVerdictRequest, SetVerdictResponse, UndoRequest, UndoResponse, UpdateNodeRequest, UpdateNodeResponse, UpdateProjectRequest, UpdateProjectResponse, WatchRequest, WatchResponse } from "./flow_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The FlowControl core API: reads, the Watch stream, and mutations.
 *
 * @generated from service flow.v1.FlowService
 */
export const FlowService = {
  typeName: "flow.v1.FlowService",
  methods: {
    /**
     * Lists projects the client can open.
     *
     * @generated from rpc flow.v1.FlowService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Loads a full, consistent snapshot of one project.
     *
     * @generated from rpc flow.v1.FlowService.GetSnapshot
     */
    getSnapshot: {
      name: "GetSnapshot",
      I: GetSnapshotRequest,
      O: GetSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Pages the event log for a project.
     *
     * @generated from rpc flow.v1.FlowService.ListEvents
     */
    listEvents: {
      name: "ListEvents",
      I: ListEventsRequest,
      O: ListEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Full-text searches nodes within a project.
     *
     * @generated from rpc flow.v1.FlowService.Search
     */
    search: {
      name: "Search",
      I: SearchRequest,
      O: SearchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary forward poll of the event log — the stateless substitute for Watch.
     *
     * @generated from rpc flow.v1.FlowService.PollChanges
     */
    pollChanges: {
      name: "PollChanges",
      I: PollChangesRequest,
      O: PollChangesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * The one long-lived call. Every client holds exactly one.
     *
     * @generated from rpc flow.v1.FlowService.Watch
     */
    watch: {
      name: "Watch",
      I: WatchRequest,
      O: WatchResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Creates a node.
     *
     * @generated from rpc flow.v1.FlowService.CreateNode
     */
    createNode: {
      name: "CreateNode",
      I: CreateNodeRequest,
      O: CreateNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates editable fields of a node.
     *
     * @generated from rpc flow.v1.FlowService.UpdateNode
     */
    updateNode: {
      name: "UpdateNode",
      I: UpdateNodeRequest,
      O: UpdateNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a node and its subtree.
     *
     * @generated from rpc flow.v1.FlowService.DeleteNode
     */
    deleteNode: {
      name: "DeleteNode",
      I: DeleteNodeRequest,
      O: DeleteNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sets a node's declared status.
     *
     * @generated from rpc flow.v1.FlowService.SetStatus
     */
    setStatus: {
      name: "SetStatus",
      I: SetStatusRequest,
      O: SetStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records an agent's condition report.
     *
     * @generated from rpc flow.v1.FlowService.ReportCondition
     */
    reportCondition: {
      name: "ReportCondition",
      I: ReportConditionRequest,
      O: ReportConditionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records a human's verdict over an agent report.
     *
     * @generated from rpc flow.v1.FlowService.SetVerdict
     */
    setVerdict: {
      name: "SetVerdict",
      I: SetVerdictRequest,
      O: SetVerdictResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds a comment to a node.
     *
     * @generated from rpc flow.v1.FlowService.AddComment
     */
    addComment: {
      name: "AddComment",
      I: AddCommentRequest,
      O: AddCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds a dependency edge.
     *
     * @generated from rpc flow.v1.FlowService.AddDependency
     */
    addDependency: {
      name: "AddDependency",
      I: AddDependencyRequest,
      O: AddDependencyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes a dependency edge.
     *
     * @generated from rpc flow.v1.FlowService.RemoveDependency
     */
    removeDependency: {
      name: "RemoveDependency",
      I: RemoveDependencyRequest,
      O: RemoveDependencyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reverses a prior event.
     *
     * @generated from rpc flow.v1.FlowService.Undo
     */
    undo: {
      name: "Undo",
      I: UndoRequest,
      O: UndoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Moves a node to a new parent and/or changes its kind.
     *
     * @generated from rpc flow.v1.FlowService.MoveNode
     */
    moveNode: {
      name: "MoveNode",
      I: MoveNodeRequest,
      O: MoveNodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a project (namespace op; returns the created Project).
     *
     * @generated from rpc flow.v1.FlowService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Edits a project's name/description.
     *
     * @generated from rpc flow.v1.FlowService.UpdateProject
     */
    updateProject: {
      name: "UpdateProject",
      I: UpdateProjectRequest,
      O: UpdateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Archives or un-archives a project.
     *
     * @generated from rpc flow.v1.FlowService.ArchiveProject
     */
    archiveProject: {
      name: "ArchiveProject",
      I: ArchiveProjectRequest,
      O: ArchiveProjectResponse,
      kind: MethodKind.Unary,
    },
  }
};

